{
 "title": "Confluent Operator",
 "description": "Confluent operator test dashboard",
 "tags": [ "testing" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Kafka CPU Load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{job=\"kafka\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Zookeeper CPU Load %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{job=\"zookeeper\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Kafka JVM Memory Usage (MB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"kafka\"}/1024/1024",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Zookeeper JVM Memory Usage (MB)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"zookeeper\"}/1024/1024",
     "legendFormat": "{{area}}"
    }
   ]
  },
  {
   "title": "Producer - Topics total in MB",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kafka_producer_producer_topic_metrics_byte_total/1024/1024",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic byte rate",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_topic_metrics_byte_rate{job=\"kafka\"}[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic send rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kafka_producer_producer_topic_metrics_record_send_rate",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Leader election time avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "kafka_server_controller_metrics_leader_election_time_avg{job=\"kafka\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}